apiVersion: v1
kind: Service
metadata:
  labels:
    app: ontology-mcp
  name: svc-ontology-mcp
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 5001
  selector:
    app: ontology-mcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ontology-mcp 
  name: ontology-mcp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontology-mcp
  template:
    metadata:
      labels:
        app: ontology-mcp
    spec:
      containers:
      - name: ontology-mcp
        image: developeronizuka/ontology-mcp:1.0.0
        #imagePullPolicy: Always
        #command: ["sleep", "infinity"]
        ports:
        - containerPort: 5001
        env:
